library(jsonlite)

data_2021 <- fromJSON("../data/2021_results.json")

season <- data_2021[['MRData']][['RaceTable']][['season']] 
# round <- ... 
# raceName <- ...
# driver <- ...
# team <- ...
# position <- ...
# points <- ...
# grid <- ...
# laps <- ...
# status <- ...

print(season)
